-- Supabase SQL Editorで実行してください。
create table if not exists public.access_requests (
  id bigint generated by default as identity primary key,
  email text not null unique,
  full_name text not null,
  status text not null default 'pending' check (status in ('pending','approved','rejected')),
  created_at timestamptz not null default now()
);

alter table public.access_requests enable row level security;

create policy "anyone can submit an access request"
  on public.access_requests for insert to anon, authenticated
  with check (char_length(full_name) between 1 and 100 and email like '%@%');

create policy "users can read their own request"
  on public.access_requests for select to authenticated
  using (lower(email) = lower(auth.jwt() ->> 'email'));

-- 管理者はSupabase Dashboardでstatusをpendingからapprovedへ変更します。
